version: '3.8'

services:
  web:
    build:
      context: .
    container_name: django_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=change-me
      - DJANGO_SETTINGS_MODULE=Monday.settings
    depends_on: []
    env_file:
      - .env
